using ECommons;
using Soulstone.Localizations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Soulstone.Managers
{
    internal class LocalizationManager
    {
        private static LocalizationManager? instance = null;
        private Dictionary<Language, Localization> localizedLanguages = new();
        public Dictionary<Language, Localization> LocalizedLanguages { get => localizedLanguages; set => localizedLanguages = value; }
        private Configuration? configuration;

        public LocalizationManager() 
        {
            LocalizedLanguages = new Dictionary<Language, Localization>();
        }

        public static LocalizationManager Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = new LocalizationManager();
                }
                return instance;
            }
        }

        public void InitLoc(Plugin plugin)
        {
            configuration = plugin.Configuration;
            Localization French = new Localization();
            French.Language = Language.Français;
            French.LocalizedStrings = new Dictionary<string, string>
            {
                //Generic Buttons
                {"AddButton", "+" },
                {"SupprButton", "-" },
                {"ThrowButton", "Lancer" },
                {"AddConfirmButton", "Ajouter" },
                //Config Window
                {"ConfigButton","Configurer" },
                {"ConfigDetailedRollsCheck", "Jets détaillés" },
                {"ConfigLanguageCombo", "Langue" },
                //Main Window Tabs
                {"RPTab", "Fiche RP" },
                {"DiceRollTab", "Lanceur de dés" },
                {"StatSheetTab","Fiche de Statistiques" },
                {"DiceSystemTab", "Système de dés" },
                {"GearTab", "Équipement" },
                {"EquipButton", "Équiper" },
                {"UnequipButton", "Déséquiper" },
                {"EquippedBadge", "ÉQUIPÉ" },
                {"GearSlotLabel", "Emplacement :" },
                {"StatModifiersLabel", "Modificateurs :" },
                {"TotalGearBonusesLabel", "Bonus totaux de l'équipement" },
                {"NoGearEquipped", "Aucun équipement" },
                {"ChooseGearTitle", "Choisir un équipement" },
                {"SlotMainHand", "Main principale" },
                {"SlotOffHand", "Main secondaire" },
                {"SlotHead", "Tête" },
                {"SlotBody", "Torse" },
                {"SlotHands", "Mains" },
                {"SlotLegs", "Jambes" },
                {"SlotFeet", "Pieds" },
                {"SlotEarrings", "Boucles d'oreilles" },
                {"SlotNeck", "Collier" },
                {"SlotWrists", "Bracelets" },
                {"SlotRing1", "Bague 1" },
                {"SlotRing2", "Bague 2" },
                {"GearSlotTooltip", "Emplacement d'équipement" },
                {"DurabilityLabel", "Durabilité :" },
                {"ItemIsGearCheckbox", "Est un équipement" },
                {"AddStatModifierButton", "Ajouter un modificateur" },
                {"StatNameHint", "Nom de stat (ex: Force, HP)" },
                {"DiceSysResourcesHeader", "Ressources Configurables" },
                {"DiceSysAddResource", "Ajouter une ressource" },
                {"DiceSysAddResourceBtn", "Ajouter une ressource..." },
                {"DiceSysEditResource", "Modifier" },
                {"DiceSysDeleteResource", "Supprimer" },
                {"DiceSysResourceName", "Nom" },
                {"DiceSysResourceMax", "Max par défaut" },
                {"DiceSysResourceFormula", "Formule de calcul :" },
                {"DiceSysResourceFormulaHint", "ex: 10 + 2 * Constitution, Force + Athlétisme, 100" },
                {"DiceSysResourceFormulaTooltip", "Formule mathématique utilisant des attributs, compétences, niveau ou constantes" },
                {"DiceSysResourceFormulaHeader", "Formule" },
                {"RecalculateResourcesBtn", "Recalculer" },
                {"RecalculateResourcesTooltip", "Recalcule les valeurs max des ressources basées sur leurs formules et statistiques actuelles" },
                {"DiceSysResourceColor", "Couleur" },
                {"DiceSysResourceModalTitleAdd", "Ajouter une ressource" },
                {"DiceSysResourceModalTitleEdit", "Modifier la ressource" },
                {"DiceSysResourceDescription", "Description :" },
                {"DiceSysResourceColorPicker", "Couleur :" },
                {"DiceSysResourceIsRequired", "Ressource requise / Principale" },
                {"DiceSysResourcePresets", "Préréglages de couleur :" },
                {"DiceSysNoResources", "Aucune ressource configurée." },
                {"DiceSysGeneralSubtitle", "Configuration de base et identité du système de dés." },
                {"DiceSysResourcesSubtitle", "Gérez les jauges, réserves et compteurs personnalisés pour les personnages." },
                {"DiceSysAugmentationsSubtitle", "Cyberware, modifications corporelles et emplacements d'implants." },
                {"DiceSysThresholdsSubtitle", "Configurez les conditions de réussite et intervalles de cible." },
                {"DiceSysFeaturesSubtitle", "Activez ou désactivez les mécaniques de jeu et fonctionnalités de personnage." },
                {"SavingThrowButton", "Jet de sauvegarde" },
                {"SavingThrowRollFormat", "Jet de sauvegarde ({0})" },
                {"StatPermTooltip", "Bonus permanent (ajoute à la valeur totale)" },
                {"StatPermHeader", "Perm" },
                {"DiceSysAugmentationsHeader", "Cyberware, Implants & Augmentations" },
                {"SystemAugmentationsCheckbox", "Activer le système de Cyberware / Augmentations" },
                {"AugmentationTitleLabel", "Titre de l'onglet :" },
                {"AugmentationSlotsHeader", "Emplacements d'augmentations" },
                {"AddAugmentationSlot", "Ajouter un emplacement" },
                {"AugmentationTab", "Cyberware" },
                {"InstallButton", "Installer" },
                {"UninstallButton", "Désinstaller" },
                {"InstalledBadge", "INSTALLÉ" },
                {"NoAugmentationsEquipped", "Aucune augmentation installée" },
                {"ChooseAugmentationTitle", "Choisir une augmentation" },
                {"CreateAugmentationModalTitle", "Créer une augmentation / implant" },
                {"ItemIsAugmentationCheckbox", "Est une augmentation / cyberware" },
                {"TotalAugmentationBonusesLabel", "Bonus totaux des augmentations" },
                {"NoAugmentationsInInventory", "Aucune augmentation disponible dans l'inventaire." },
                {"AugmentationSlotTooltip", "Emplacement d'augmentation" },
                {"AugmentationBadge", "Cyberware" },
                {"SlotNeural", "Neural" },
                {"SlotOptics", "Optique" },
                {"SlotCranial", "Crânien" },
                {"SlotTorso", "Torse" },
                {"SlotArms", "Bras" },
                {"SlotSubdermal", "Sous-cutané" },
                {"SlotInternal", "Interne" },
                {"StatCategoryLabel", "Type de stat :" },
                {"StatCategoryAttribute", "Attribut" },
                {"StatCategorySkill", "Compétence" },
                {"StatCategoryAbility", "Capacité" },
                {"StatCategoryResource", "Ressource" },
                {"StatCategoryCustom", "Personnalisé" },
                {"SelectExistingStat", "Choisir une stat existante..." },
                {"NoCharLoadedGearMessage", "Aucun personnage chargé. Créez ou chargez une fiche d'abord." },
                {"CreateGearModalTitle", "Créer un équipement" },
                {"GearBadge", "Équipement" },
                {"NoGearInInventory", "Aucun équipement disponible dans l'inventaire." },
                {"GearBonusTooltip", "Bonus d'équipement" },
                {"GearBonusFormat", "+{0} (Équipement)" },
                //Initiative System
                {"InitiativeTrackerTitle", "Suivi d'Initiative" },
                {"InitiativeTab", "Initiative" },
                {"InitiativeRound", "Tour de table : {0}" },
                {"InitiativeTurn", "Tour : {0}" },
                {"InitiativeNextTurn", "Tour suivant" },
                {"InitiativePrevTurn", "Tour précédent" },
                {"InitiativeReset", "Réinitialiser les tours" },
                {"InitiativeClearAll", "Tout effacer" },
                {"InitiativeSortAsc", "Croissant" },
                {"InitiativeSortDesc", "Décroissant" },
                {"InitiativeAddParticipant", "Ajouter un participant" },
                {"InitiativeParticipantName", "Nom" },
                {"InitiativeValue", "Initiative" },
                {"InitiativeBonus", "Bonus" },
                {"InitiativeNotes", "Notes" },
                {"InitiativeAddSelf", "S'ajouter / Lancer" },
                {"InitiativeRollInitiative", "Lancer l'initiative" },
                {"InitiativeActiveTurn", "Tour actif" },
                {"InitiativeNoParticipants", "Aucun participant dans le suivi d'initiative." },
                {"InitiativeConfigHeader", "Configuration de l'Initiative" },
                {"InitiativeConfigSubtitle", "Définissez l'attribut ou la compétence de la fiche utilisé pour lancer l'initiative." },
                {"InitiativeStatTypeLabel", "Source d'initiative :" },
                {"InitiativeStatNameLabel", "Statistique sélectionnée :" },
                {"InitiativeNone", "Aucune (d20 brut)" },
                {"InitiativeAttribute", "Attribut" },
                {"InitiativeSkill", "Compétence" },
                {"InitiativeTurnNotificationFormat", "C'est au tour de {0} !" },
                {"InitiativeRollChatFormat", "Jet d'initiative ({0}) : {1}" },
                {"InitiativeOpenTracker", "Suivi d'Initiative" },
                {"BuffsHeader", "Effets & Buffs" },
                {"BuffsColumn", "Buffs / Debuffs" },
                {"AddBuffButton", "+ Buff" },
                {"BuffNameLabel", "Nom de l'effet :" },
                {"BuffDurationLabel", "Durée (tours) :" },
                {"BuffTurnsFormat", "{0} t" },
                {"BuffTargetStatLabel", "Statistique ciblée :" },
                {"BuffValueLabel", "Valeur / Modificateur :" },
                {"BuffIsDebuffLabel", "Est un debuff" },
                {"BuffExpiredNotificationFormat", "L'effet '{0}' sur {1} a expiré !" },
                {"NoActiveBuffs", "Aucun effet actif." },
                {"BuffModalTitle", "Ajouter un Buff / Debuff" },
                {"BuffDurationRemaining", "Durée restante : {0} tours" },
                {"BuffTickButton", "Décrémenter les tours" },
                {"BuffStatNameHint", "ex: Force, Attaque, Initiative, Santé, Tout" },
                //CharSheet Tab First part (Char Info)
                {"EditCharsheetCheck", "Editer la fiche de personnage" },
                {"NewCharnameField", "Nom du nouveau personnage" },
                {"NewCharButton", "Créer une nouvelle fiche de personnage" },
                {"SaveCharsheetButton", "Sauvegarder la fiche de personnage" },
                {"CharsheetChoose", "Charger une fiche de personnage" },
                {"CharFullnameField", "Nom/Prénom :" },
                {"CharNicknameField", "Surnom :" },
                {"CharSpecieField", "Race :" },
                {"CharSubSpecieField", "Sous-race :" },
                {"CharClassField", "Classe :" },
                {"CharSexField", "Sexe :" },
                {"CharGenderField", "Genre :" },
                {"CharPronounsField", "Pronoms :" },
                {"CharAgeField", "Âge :" },
                //CharSheet Tab Second part (HRP)
                {"PlayerOOCInfo", "Infos HRP :" },
                {"PlayerTimezone", "Fuseau Horaire :" },
                {"PlayerAvailability", "Disponibilité :" },
                //Charsheet Tab, third part (Appearance)
                {"CharHeightField", "Taille :" },
                {"CharWeightField", "Poids :" },
                {"CharBuildField", "Corpulence :" },
                {"CharEyeColorField", "Couleur des yeux :" },
                {"CharHairColorField", "Couleur des cheveux :" },
                {"CharSkinColorField", "Couleur de peau :" },
                {"CharScarsField", "Cicatrices :" },
                {"CharTatooField", "Tatouages :" },
                {"CharOtherQuirkField", "Autre(s) particulrité(s)" },
                //Charsheet Tab, fourth part (Quick Looks)
                {"QuickLookField1", "Aperçu rapide :" },
                {"QuickLookField2", "Aperçu rapide 2 :" },
                {"QuickLookField3", "Aperçu rapide 3 :" },
                {"QuickLookField4", "Aperçu rapide 4 :" },
                {"QuickLookField5", "Aperçu rapide 5 :" },
                //Charsheet Tab, Fifth part (Background)
                {"CharBirthplaceField", "Lieu de Naissance :" },
                {"CharOriginField", "Origine :" },
                {"CharAffiliationField", "Affiliation :" },
                {"CharWorkField", "Metier :" },
                {"CharReputationField", "Réputation :" },
                {"CharFamilyRelationTab", "Relations familiales :" },
                {"CharFriendsTab", "Relations amicales :" },
                {"CharEnemiesTab", "Ennemis :" },
                {"CharBackgroundField", "Histoire personnelle :" },
                //Family member popup
                {"MemberNameField", "Nom du membre" },
                {"MemberDescriptionField", "Description" },
                //Friend popup
                {"FriendNameField", "Nom de l'ami" },
                {"FriendDescriptionField", "Description" },
                //Enemy Popup
                {"EnemyNameField", "Nom de l'ennemi" },
                {"EnemyDescriptionField", "Description" },
                //Dice Tab
                {"RollInputLabel", "Jet" },
                {"AdvantageCheckbox", "Avantage" },
                {"DisadvantageCheckbox", "Désavantage" },
                //Stat Tab
                {"SystemDiceTypeLabel", "Type de dé du système :" },
                {"EditStatCheckbox", "Editer les stats du personnage" },
                {"SaveStatButton", "Sauvegarder la fiche de personnage" },
                {"AdvantageRollCheckbox", "Jet avec avantage" },
                {"DisadvantageRollCheckbox", "Jet avec désavantage" },
                {"HealthLabel", "Santé :" },
                {"ManaLabel", "Mana :" },
                {"ClassLabel", "Classe :" },
                {"LevelLabel", "Niveau :" },
                {"XPLabel", "XP :" },
                {"AttributeLabel", "Attributs :" },
                {"SkillLabel", "Compétences :" },
                {"AbilityLabel", "Capacités :" },
                {"NewAttributeNameLabel", "Nom de l'attribut" },
                {"NewAttributeValueLabel", "Valeur" },
                {"NewSkillName", "Nom de la compétence" },
                {"NewSkillValue", "Valeur" },
                {"NewLinkedAttribute", "Attribut lié" },
                {"NewAbilityName", "Nom de la capacité" },
                {"NewAbilityValue", "Valeur" },
                {"NewLinkedSkill", "Compétence lié" },
                {"SkillLinkText", "(lié à " },
                {"AbilityLinkText", "(lié à " },
                //Dice System Tab
                {"DiceSystemSaveButton", "Sauvegarder le système de dés" },
                {"DiceSystemChoose", "Charger un système de dés" },
                {"DiceSystemNameLabel", "Nom du système de dés :" },
                {"SystemTypeCombo", "Type de système de dés" },
                {"DiceTypeCombo", "Type de dé :" },
                {"SuccessThresholdLabel", "Seuil de réussite (pour les systèmes à pool de dés) :" },
                {"SuccessIntervalLabel", "Interval de réussite (pour les systèmes pourcentage) :" },
                {"DndStyleAttrCheckbox", "Attributs de style DnD" },
                {"SkillUniqueAttrCheckbox", "Compétence liée à un seul attribut" },
                {"AbilityUniqueAttrCheckbox", "Capacité liée à un seul attribut" },
                {"AbilityUniqueSkillCheckbox", "Capacité lieée à une seule compétence" },
                {"DnDStyleSavesCheckbox", "Le système gère les jets de sauvegarde" },
                {"DnDStyleAdvDisadvCheckbox", "Le système gère l'avantage et le désavantage" },
                {"DnDStyleManaCheckbox", "Le système gère les points de mana ou de ressources" },
                {"DnDStyleClassesCheckbox", "Le système gère les classes" },
                {"TempBonusCheckbox", "Le système gère les bonus temporaires" },
                {"PermBonusCheckbox", "Le système gère les bonus permanents" },
                {"EpicAttributesCheckbox", "Le système gère les attributs épiques" },
                {"ConfigEpicBonusCheck", "Afficher les bonus épiques" },
                {"ConfigShowEpicBonus", "Afficher les bonus épiques" },
                {"StatValueHeader", "Val." },
                {"StatTempHeader", "Temp (+Dés)" },
                {"StatEpicHeader", "Épique (+Succès)" },
                {"StatValueTooltip", "Valeur de base" },
                {"StatTempTooltip", "Bonus temporaire (ajoute au nombre de dés)" },
                {"StatEpicTooltip", "Bonus épique (ajoute aux succès bruts pour pool de dés)" },
                //Inventory Tab & Pictures
                {"InventoryTab", "Inventaire" },
                {"CharPictureField", "Portrait / Image :" },
                {"CharPictureUrl", "URL ou chemin de l'image" },
                {"CharPictureBrowse", "Parcourir..." },
                {"CharPictureClear", "Effacer" },
                {"InventoryCapacityLabel", "Capacité :" },
                {"InventoryUnlimited", "Illimité" },
                {"InventorySlotsUsed", "{0} / {1} emplacements" },
                {"InventoryAddItem", "Créer un objet" },
                {"InventoryManageTypes", "Gérer les types" },
                {"InventorySearchPlaceholder", "Rechercher..." },
                {"InventoryFilterType", "Type :" },
                {"InventoryAllTypes", "Tous les types" },
                {"InventorySortBy", "Trier par :" },
                {"InventorySortName", "Nom" },
                {"InventorySortType", "Type" },
                {"InventorySortQuantity", "Quantité" },
                {"InventorySortRarity", "Rareté" },
                {"InventoryNoItems", "Aucun objet dans l'inventaire." },
                {"InventoryItemDetails", "Détails de l'objet" },
                {"InventorySelectItemPrompt", "Sélectionnez un objet pour afficher ses détails." },
                {"InventoryItemName", "Nom :" },
                {"InventoryItemType", "Type :" },
                {"InventoryItemQuantity", "Quantité :" },
                {"InventoryItemMaxStack", "Pile max :" },
                {"InventoryItemRarity", "Rareté :" },
                {"InventoryItemWeight", "Poids :" },
                {"InventoryItemDescription", "Description :" },
                {"InventoryItemEffect", "Effet(s) :" },
                {"InventoryItemImage", "Image (URL ou fichier local) :" },
                {"InventoryItemCustomProps", "Propriétés personnalisées :" },
                {"InventoryAddProperty", "+ Propriété" },
                {"InventoryPropKey", "Clé" },
                {"InventoryPropValue", "Valeur" },
                {"InventoryItemUse", "Utiliser" },
                {"InventoryItemDuplicate", "Dupliquer" },
                {"InventoryItemEdit", "Modifier" },
                {"InventoryItemDelete", "Supprimer" },
                {"InventoryExportJson", "Copier JSON" },
                {"InventorySaveItem", "Enregistrer l'objet" },
                {"InventoryEditItemTitle", "Modifier l'objet" },
                {"InventoryCreateItemTitle", "Nouvel objet" },
                {"InventoryManageTypesTitle", "Types d'objets personnalisés" },
                {"InventoryNewTypeName", "Nom du nouveau type" },
                {"InventoryAddTypeBtn", "Ajouter le type" },
                {"InventoryCustomCapacity", "Capacité personnalisée :" },
                {"SystemInventoryLimitCheckbox", "Le système gère une limite d'inventaire" },
                {"SystemInventorySlotsLabel", "Emplacements max d'inventaire :" },
                {"InventoryImportJson", "Importer" },
                {"InventoryImportTitle", "Importer des objets" },
                {"InventoryImportFileBtn", "Fichier JSON..." },
                {"InventoryImportRawText", "Ou collez le texte JSON brut :" },
                {"InventoryImportConfirmBtn", "Importer dans l'inventaire" },
                {"InventoryImportSuccess", "{0} objet(s) importé(s) avec succès !" },
                {"InventoryImportError", "Erreur lors de l'importation : {0}" },
                {"InventoryItemIsUsable", "Objet utilisable" },
                {"InventoryItemFormula", "Formule d'utilisation (ex: 2d4+2, 10) :" },
                {"InventoryItemFormulaHint", "ex: 2d4+2, 1d8+3, 10" },
                {"InventoryItemNotUsable", "Cet objet n'est pas utilisable." },
                {"InventoryItemUsedMessage", "A utilisé {0}" },
                // Generic / Buttons / Dialogs
                {"CancelButton", "Annuler" },
                {"CloseButton", "Fermer" },
                {"DeleteButton", "Supprimer" },
                {"RemoveTooltip", "Supprimer" },
                {"NoneText", "Aucun" },
                {"NoneOption", "(Aucun)" },
                {"SelectButton", "Sélectionner" },
                {"EditButton", "Modifier" },
                {"UnnamedCharacter", "Personnage sans nom" },
                {"AgeYearsFormat", "{0} ans" },
                {"ChooseCharPicPickerTitle", "Choisir une image de personnage" },
                {"ChooseCharSheetPickerTitle", "Charger une fiche de personnage" },
                {"BadgeEditing", "ÉDITION" },
                {"BadgeViewing", "AFFICHAGE" },
                {"NewCharnameDefault", "Nouveau personnage" },
                {"NoCharLoadedMessage", "Aucun personnage chargé. Créez ou chargez une fiche ci-dessus." },
                // Config Window
                {"ConfigWindowTitle", "Soulstone - Paramètres" },
                {"ConfigRollDisplayHeader", "Paramètres d'affichage des jets" },
                {"ConfigLocalizationHeader", "Langue & Localisation" },
                // Stat Window
                {"NoCharLoadedStatsMessage", "Aucun personnage chargé. Chargez ou créez une fiche d'abord." },
                {"SystemDiceBadgeFormat", "Dé : {0}" },
                {"NoAttributesDefined", "Aucun attribut défini." },
                {"NoSkillsDefined", "Aucune compétence définie." },
                {"NoAbilitiesDefined", "Aucune capacité définie." },
                // Dice System Window
                {"NoDiceSysLoadedMessage", "Aucun système de dés chargé." },
                {"ChooseDiceSysPickerTitle", "Choisir un fichier de système de dés" },
                {"DiceSysGeneralConfigHeader", "Configuration générale" },
                {"DiceSysThresholdsHeader", "Règles de réussite & cibles" },
                {"DiceSysFeaturesHeader", "Mécaniques & règles optionnelles" },
                {"TableHeaderLabel", "Libellé" },
                {"TableHeaderValue", "Valeur" },
                // Dice Window
                {"QuickDiceHeader", "Dés rapides" },
                {"DiceRollFormulaHint", "ex: 2d6+4, 1d20+5" },
                {"ClearFormulaTooltip", "Effacer la formule" },
                {"BadgeAdvantage", "AVANTAGE" },
                {"BadgeDisadvantage", "DÉSAVANTAGE" },
                {"NormalRollText", "Jet normal" },
                {"RollHistoryHeader", "Historique des jets" },
                {"ClearHistoryButton", "Effacer l'historique" },
                {"NoRollHistoryMessage", "Aucun jet enregistré pour le moment lors de cette session." },
                // Inventory Window
                {"NoCharLoadedInventoryMessage", "Aucun personnage chargé. Créez ou chargez une fiche de personnage d'abord." },
                {"InventoryUnnamedItem", "Objet sans nom" },
                {"InventoryItemQtyFormat", "Qté : {0} / {1}" },
                {"InventoryItemWeightFormat", "Poids : {0:F1}" },
                {"InventoryItemUsableBadge", "Utilisable" },
                {"InventoryChoosePicPickerTitle", "Choisir une image d'objet" },
                {"InventoryStandardTypesHeader", "Types standards :" },
                {"InventoryCustomTypesHeader", "Types personnalisés :" },
                {"InventoryNoCustomTypesMessage", "Aucun type personnalisé défini." },
                {"InventoryDeleteConfirmTitle", "Confirmer la suppression" },
                {"InventoryDeleteConfirmPrompt", "Êtes-vous sûr de vouloir supprimer '{0}' ?" },
                {"InventoryImportSelectJsonPrompt", "Sélectionnez un fichier JSON contenant un objet ou une liste d'objets :" },
                {"InventoryImportPickerTitle", "Importer des objets depuis un fichier JSON" },
                {"InventoryItemCopySuffix", " (Copie)" },
                // Standard Item Types
                {"ItemTypeGeneral", "Général" },
                {"ItemTypeConsumable", "Consommable" },
                {"ItemTypeWeapon", "Arme" },
                {"ItemTypeArmor", "Armure" },
                {"ItemTypeAccessory", "Accessoire" },
                {"ItemTypeMaterial", "Matériau" },
                {"ItemTypeKeyItem", "Objet clé" },
                {"ItemTypeQuest", "Quête" },
                {"ItemTypeMiscellaneous", "Divers" },
                // Rarities
                {"RarityCommon", "Commun" },
                {"RarityUncommon", "Peu commun" },
                {"RarityRare", "Rare" },
                {"RarityEpic", "Épique" },
                {"RarityLegendary", "Légendaire" },
                {"RarityArtifact", "Artéfact" },
                // File Browser Window
                {"FileBrowserTitle", "Sélectionner un fichier" },
                {"FileBrowserGoUpTooltip", "Remonter d'un dossier" },
                {"FileBrowserRefreshTooltip", "Actualiser" },
                {"FileBrowserPathInputTooltip", "Entrez un chemin et appuyez sur Entrée pour naviguer" },
                {"FileBrowserFilterHint", "Filtrer les fichiers..." },
                {"FileBrowserUrlLabel", "URL :" },
                {"FileBrowserUrlHint", "https://exemple.com/image.png (ou entrez une URL directe d'image)" },
                {"FileBrowserUrlTooltip", "Entrez une URL web pour l'image" },
                {"FileBrowserPreviewButton", "Aperçu" },
                {"FileBrowserUseUrlButton", "Utiliser l'URL" },
                {"FileBrowserQuickAccessHeader", "Accès rapide" },
                {"FileBrowserPinnedHeader", "Épinglé" },
                {"FileBrowserUnpinContext", "Désépingler de l'accès rapide" },
                {"FileBrowserPinContext", "Épingler à l'accès rapide" },
                {"FileBrowserRecentHeader", "Récents" },
                {"FileBrowserPictures", "Images" },
                {"FileBrowserDocuments", "Documents" },
                {"FileBrowserDesktop", "Bureau" },
                {"FileBrowserDownloads", "Téléchargements" },
                {"FileBrowserHome", "Dossier personnel" },
                {"FileBrowserLocalDisk", "Disque local" },
                {"FileBrowserFilesHeader", "Fichiers" },
                {"FileBrowserSortName", "Nom" },
                {"FileBrowserSortDate", "Date de modification" },
                {"FileBrowserSortSize", "Taille" },
                {"FileBrowserSortType", "Type" },
                {"FileBrowserSortDesc", "Décroissant" },
                {"FileBrowserSortAsc", "Croissant" },
                {"FileBrowserOpenContext", "Ouvrir" },
                {"FileBrowserNoFilesFound", "Aucun fichier trouvé" },
                {"FileBrowserPreviewHeader", "Aperçu" },
                {"FileBrowserNoPreviewPrompt", "Sélectionnez un fichier ou entrez une URL pour prévisualiser" },
                {"FileBrowserWebImageUrl", "URL de l'image web" },
                {"FileBrowserLoadingPreview", "Téléchargement / Chargement de l'aperçu..." },
                {"FileBrowserFileNotFound", "Fichier non trouvé" },
                {"FileBrowserSelectedLabel", "Sélectionné : {0}" },
                {"FileBrowserNoFileSelected", "Aucun fichier sélectionné" },
                // Group Management Window
                {"GroupManagementTitle", "Gestion de groupe" },
                {"GroupManagementSubtitle", "Surveillance de l'équipe, jauges de ressources et synchronisation en temps réel." },
                {"GroupOpenWindow", "Groupe" },
                {"OpenGroupWindowTooltip", "Ouvrir la gestion de groupe" },
                {"GroupStatusConnected", "Soulstone Connecté" },
                {"GroupStatusNoSoulstone", "Sans Soulstone" },
                {"GroupRulesetInSync", "Règles synchronisées" },
                {"GroupRulesetOutOfSync", "Règles différentes" },
                {"GroupBadgeLeader", "MD / Chef" },
                {"GroupRefreshRoster", "Actualiser le groupe" },
                {"GroupBroadcastRuleset", "Diffuser les règles au groupe" },
                {"GroupSyncInitiative", "Importer dans le Suivi d'Initiative" },
                {"GroupBroadcastVitals", "Partager mes jauges" },
                {"GroupAdoptRuleset", "Adopter les règles du MD" },
                {"GroupRevertRuleset", "Restaurer mes règles locales" },
                {"GroupLastRoll", "Dernier jet :" },
                {"GroupActiveBuffs", "Effets actifs :" },
                {"GroupHealth", "Santé" },
                {"GroupMana", "Mana" },
                {"GroupNoMembers", "Aucun membre du groupe détecté." },
                {"GroupDMControls", "Commandes du Maître du Jeu" },
                {"GroupPlayerControls", "Actions du joueur" },
                {"GroupSyncedFromDM", "Règles synchronisées du MD" },
                {"GroupRevertRulesetPrompt", "Règles locales restaurées." },
                {"GroupAdoptConfirmPrompt", "Règles du MD adoptées pour la session." },
                {"InitiativeDMBadge", "MD / Hôte" },
                {"InitiativeMemberBadge", "Membre synchronisé" },
                {"InitiativeDMRequired", "Seul le chef de groupe / MD contrôle le flux des tours." },
                // Plugin
                {"PluginCommandHelp", "Ouvre la fenêtre principale. Utilisez '/soulstone init' pour l'initiative et '/soulstone group' pour le groupe." }
            };

            Localization English = new Localization();
            English.Language = Language.English;
            English.LocalizedStrings = new Dictionary<string, string>
            {
                //Generic Buttons
                {"AddButton", "+" },
                {"SupprButton", "-" },
                {"ThrowButton", "Roll" },
                {"AddConfirmButton", "Add" },
                //Config Window
                {"ConfigButton","Config" },
                {"ConfigDetailedRollsCheck", "Detailed Dice throws" },
                {"ConfigLanguageCombo", "Language" },
                //Main Window Tabs
                {"RPTab", "RP Sheet" },
                {"DiceRollTab", "Dice Thrower" },
                {"StatSheetTab","Stat Sheet" },
                {"DiceSystemTab", "Dice System" },
                {"GearTab", "Gear" },
                {"EquipButton", "Equip" },
                {"UnequipButton", "Unequip" },
                {"EquippedBadge", "EQUIPPED" },
                {"GearSlotLabel", "Slot:" },
                {"StatModifiersLabel", "Stat Modifiers:" },
                {"TotalGearBonusesLabel", "Total Gear Bonuses" },
                {"NoGearEquipped", "No gear equipped" },
                {"ChooseGearTitle", "Choose Gear" },
                {"SlotMainHand", "Main Hand" },
                {"SlotOffHand", "Off Hand" },
                {"SlotHead", "Head" },
                {"SlotBody", "Body" },
                {"SlotHands", "Hands" },
                {"SlotLegs", "Legs" },
                {"SlotFeet", "Feet" },
                {"SlotEarrings", "Earrings" },
                {"SlotNeck", "Neck" },
                {"SlotWrists", "Wrists" },
                {"SlotRing1", "Ring 1" },
                {"SlotRing2", "Ring 2" },
                {"GearSlotTooltip", "Equipment Slot" },
                {"DurabilityLabel", "Durability:" },
                {"ItemIsGearCheckbox", "Is Equipment / Gear" },
                {"AddStatModifierButton", "Add Stat Modifier" },
                {"StatNameHint", "Stat name (e.g. Strength, HP)" },
                {"DiceSysResourcesHeader", "Configurable Resources" },
                {"DiceSysAddResource", "Add Resource" },
                {"DiceSysAddResourceBtn", "Add Resource..." },
                {"DiceSysEditResource", "Edit" },
                {"DiceSysDeleteResource", "Delete" },
                {"DiceSysResourceName", "Name" },
                {"DiceSysResourceMax", "Default Max" },
                {"DiceSysResourceFormula", "Calculation Formula:" },
                {"DiceSysResourceFormulaHint", "e.g. 10 + 2 * Constitution, Strength + Athletics, 100" },
                {"DiceSysResourceFormulaTooltip", "Mathematical formula using attributes, skills, level, or constants" },
                {"DiceSysResourceFormulaHeader", "Formula" },
                {"RecalculateResourcesBtn", "Recalculate" },
                {"RecalculateResourcesTooltip", "Recalculates resource max values based on their formulas and current stats" },
                {"DiceSysResourceColor", "Color" },
                {"DiceSysResourceModalTitleAdd", "Add Resource" },
                {"DiceSysResourceModalTitleEdit", "Edit Resource" },
                {"DiceSysResourceDescription", "Description :" },
                {"DiceSysResourceColorPicker", "Color :" },
                {"DiceSysResourceIsRequired", "Required / Core Resource" },
                {"DiceSysResourcePresets", "Color Presets :" },
                {"DiceSysNoResources", "No custom resources configured." },
                {"DiceSysGeneralSubtitle", "Core settings and identity of the dice system." },
                {"DiceSysResourcesSubtitle", "Manage vitals, gauges, pools and custom meters for characters." },
                {"DiceSysAugmentationsSubtitle", "Cyberware, body modifications, and implant equipment slots." },
                {"DiceSysThresholdsSubtitle", "Configure success conditions and target intervals." },
                {"DiceSysFeaturesSubtitle", "Enable or disable specific gameplay mechanics and character features." },
                {"SavingThrowButton", "Saving Throw" },
                {"SavingThrowRollFormat", "Saving Throw ({0})" },
                {"StatPermTooltip", "Permanent Bonus (adds to total stat value)" },
                {"StatPermHeader", "Perm" },
                {"DiceSysAugmentationsHeader", "Cyberware, Implants & Augmentations" },
                {"SystemAugmentationsCheckbox", "Enable Cyberware / Augmentations System" },
                {"AugmentationTitleLabel", "Tab Title:" },
                {"AugmentationSlotsHeader", "Augmentation Slots" },
                {"AddAugmentationSlot", "Add Slot" },
                {"AugmentationTab", "Cyberware" },
                {"InstallButton", "Install" },
                {"UninstallButton", "Uninstall" },
                {"InstalledBadge", "INSTALLED" },
                {"NoAugmentationsEquipped", "No augmentations installed" },
                {"ChooseAugmentationTitle", "Choose Augmentation" },
                {"CreateAugmentationModalTitle", "Create Augmentation / Cyberware" },
                {"ItemIsAugmentationCheckbox", "Is Augmentation / Cyberware" },
                {"TotalAugmentationBonusesLabel", "Total Augmentation Bonuses" },
                {"NoAugmentationsInInventory", "No augmentations available in inventory." },
                {"AugmentationSlotTooltip", "Augmentation Slot" },
                {"AugmentationBadge", "Cyberware" },
                {"SlotNeural", "Neural" },
                {"SlotOptics", "Optics" },
                {"SlotCranial", "Cranial" },
                {"SlotTorso", "Torso" },
                {"SlotArms", "Arms" },
                {"SlotSubdermal", "Subdermal" },
                {"SlotInternal", "Internal" },
                {"StatCategoryLabel", "Stat Category:" },
                {"StatCategoryAttribute", "Attribute" },
                {"StatCategorySkill", "Skill" },
                {"StatCategoryAbility", "Ability" },
                {"StatCategoryResource", "Resource" },
                {"StatCategoryCustom", "Custom" },
                {"SelectExistingStat", "Select existing stat..." },
                {"NoCharLoadedGearMessage", "No character loaded. Create or load a character sheet first." },
                {"CreateGearModalTitle", "Create Gear" },
                {"GearBadge", "Gear" },
                {"NoGearInInventory", "No matching gear available in inventory." },
                {"GearBonusTooltip", "Gear Bonus" },
                {"GearBonusFormat", "+{0} (Gear)" },
                //Initiative System
                {"InitiativeTrackerTitle", "Initiative Tracker" },
                {"InitiativeTab", "Initiative" },
                {"InitiativeRound", "Round: {0}" },
                {"InitiativeTurn", "Turn: {0}" },
                {"InitiativeNextTurn", "Next Turn" },
                {"InitiativePrevTurn", "Previous Turn" },
                {"InitiativeReset", "Reset Turns" },
                {"InitiativeClearAll", "Clear All" },
                {"InitiativeSortAsc", "Ascending" },
                {"InitiativeSortDesc", "Descending" },
                {"InitiativeAddParticipant", "Add Participant" },
                {"InitiativeParticipantName", "Name" },
                {"InitiativeValue", "Initiative" },
                {"InitiativeBonus", "Bonus" },
                {"InitiativeNotes", "Notes" },
                {"InitiativeAddSelf", "Add Self / Roll" },
                {"InitiativeRollInitiative", "Roll Initiative" },
                {"InitiativeActiveTurn", "Active Turn" },
                {"InitiativeNoParticipants", "No participants in initiative tracker." },
                {"InitiativeConfigHeader", "Initiative Configuration" },
                {"InitiativeConfigSubtitle", "Define the sheet attribute or skill used to roll initiative." },
                {"InitiativeStatTypeLabel", "Initiative Source:" },
                {"InitiativeStatNameLabel", "Selected Stat:" },
                {"InitiativeNone", "None (Flat d20)" },
                {"InitiativeAttribute", "Attribute" },
                {"InitiativeSkill", "Skill" },
                {"InitiativeTurnNotificationFormat", "{0}'s Turn!" },
                {"InitiativeRollChatFormat", "Rolled Initiative ({0}): {1}" },
                {"InitiativeOpenTracker", "Initiative Tracker" },
                {"BuffsHeader", "Effects & Buffs" },
                {"BuffsColumn", "Buffs / Debuffs" },
                {"AddBuffButton", "+ Buff" },
                {"BuffNameLabel", "Effect Name:" },
                {"BuffDurationLabel", "Duration (turns):" },
                {"BuffTurnsFormat", "{0} t" },
                {"BuffTargetStatLabel", "Target Stat:" },
                {"BuffValueLabel", "Value / Modifier:" },
                {"BuffIsDebuffLabel", "Is Debuff" },
                {"BuffExpiredNotificationFormat", "The effect '{0}' on {1} has expired!" },
                {"NoActiveBuffs", "No active effects." },
                {"BuffModalTitle", "Add Buff / Debuff" },
                {"BuffDurationRemaining", "Remaining duration: {0} turns" },
                {"BuffTickButton", "Tick Turn" },
                {"BuffStatNameHint", "e.g. Strength, Attack, Initiative, Health, All" },
                //CharSheet Tab First part (Char Info)
                {"EditCharsheetCheck", "Edit Character Sheet" },
                {"NewCharnameField", "New Character name" },
                {"NewCharButton", "Create new character sheet" },
                {"SaveCharsheetButton", "Save Character Sheet" },
                {"CharsheetChoose", "Load Character Sheet" },
                {"CharFullnameField", "Fullname :" },
                {"CharNicknameField", "Nickname :" },
                {"CharSpecieField", "Specie :" },
                {"CharSubSpecieField", "Sub-specie :" },
                {"CharClassField", "Job :" },
                {"CharSexField", "Sex :" },
                {"CharGenderField", "Gender :" },
                {"CharPronounsField", "Pronouns :" },
                {"CharAgeField", "Age :" },
                //CharSheet Tab Second part (HRP)
                {"PlayerOOCInfo", "OOC Info :" },
                {"PlayerTimezone", "Timezone :" },
                {"PlayerAvailability", "Availability :" },
                //Charsheet Tab, third part (Appearance)
                {"CharHeightField", "Height :" },
                {"CharWeightField", "Weight :" },
                {"CharBuildField", "Build :" },
                {"CharEyeColorField", "Eye color :" },
                {"CharHairColorField", "Hair color :" },
                {"CharSkinColorField", "Skin color :" },
                {"CharScarsField", "Scars :" },
                {"CharTatooField", "Tatoos :" },
                {"CharOtherQuirkField", "Other Quirks" },
                //Charsheet Tab, fourth part (Quick Looks)
                {"QuickLookField1", "Quick look :" },
                {"QuickLookField2", "Quick look 2 :" },
                {"QuickLookField3", "Quick look 3 :" },
                {"QuickLookField4", "Quick look 4 :" },
                {"QuickLookField5", "Quick look 5 :" },
                //Charsheet Tab, Fifth part (Background)
                {"CharBirthplaceField", "Birth place :" },
                {"CharOriginField", "Origin :" },
                {"CharAffiliationField", "Affiliation :" },
                {"CharWorkField", "Work :" },
                {"CharReputationField", "Reputation :" },
                {"CharFamilyRelationTab", "Family :" },
                {"CharFriendsTab", "Friends :" },
                {"CharEnemiesTab", "Enemies :" },
                {"CharBackgroundField", "Background :" },
                //Family member popup
                {"MemberNameField", "Member Name" },
                {"MemberDescriptionField", "Description" },
                //Friend popup
                {"FriendNameField", "Friend's name" },
                {"FriendDescriptionField", "Description" },
                //Enemy Popup
                {"EnemyNameField", "Enemy's name" },
                {"EnemyDescriptionField", "Description" },
                //Dice Window
                {"RollInputLabel", "Dice Roll" },
                {"AdvantageCheckbox", "Advantage" },
                {"DisadvantageCheckbox", "Disadvantage" },
                //Stat Tab
                {"SystemDiceTypeLabel", "System dice type :" },
                {"EditStatCheckbox", "Edit stats" },
                {"SaveStatButton", "Save stats" },
                {"AdvantageRollCheckbox", "Roll with advantage" },
                {"DisadvantageRollCheckbox", "Roll with disadvantage" },
                {"HealthLabel", "Health :" },
                {"ManaLabel", "Mana :" },
                {"ClassLabel", "Class :" },
                {"LevelLabel", "Level :" },
                {"XPLabel", "XP :" },
                {"AttributeLabel", "Attributes :" },
                {"SkillLabel", "Skills :" },
                {"AbilityLabel", "Abilities :" },
                {"NewAttributeNameLabel", "Attribute name" },
                {"NewAttributeValueLabel", "Value" },
                {"NewSkillName", "Skill name" },
                {"NewSkillValue", "Value" },
                {"NewLinkedAttribute", "Linked attribute" },
                {"NewAbilityName", "Skill name" },
                {"NewAbilityValue", "Value" },
                {"NewLinkedSkill", "Linked Skill" },
                {"SkillLinkText", " (linked to " },
                {"AbilityLinkText", " (linked to " },
                //Dice System Tab
                {"DiceSystemSaveButton", "Save dice system" },
                {"DiceSystemChoose", "Load dice system" },
                {"DiceSystemNameLabel", "System name :" },
                {"SystemTypeCombo", "System type :" },
                {"DiceTypeCombo", "Dice Type :" },
                {"SuccessThresholdLabel", "Success Threshold (for dice pool systems) :" },
                {"SuccessIntervalLabel", "Success Interval (for percentile dice systems) :" },
                {"DndStyleAttrCheckbox", "DnD style attributes" },
                {"SkillUniqueAttrCheckbox", "Skill linked only to one attribute" },
                {"AbilityUniqueAttrCheckbox", "Ability linked only to one attribute" },
                {"AbilityUniqueSkillCheckbox", "Ability linked only to one skill" },
                {"DnDStyleSavesCheckbox", "System has saving throws" },
                {"DnDStyleAdvDisadvCheckbox", "System handles advantage and disadvantage" },
                {"DnDStyleManaCheckbox", "System handles mana or resource points" },
                {"DnDStyleClassesCheckbox", "System handles classes" },
                {"TempBonusCheckbox", "System handles temporary bonuses" },
                {"PermBonusCheckbox", "System handles permanent bonuses" },
                {"EpicAttributesCheckbox", "System handles epic attributes" },
                {"ConfigEpicBonusCheck", "Show epic bonuses" },
                {"ConfigShowEpicBonus", "Show epic bonuses" },
                {"StatValueHeader", "Val" },
                {"StatTempHeader", "Temp (+Dice)" },
                {"StatEpicHeader", "Epic (+Succ)" },
                {"StatValueTooltip", "Flat / Base Value" },
                {"StatTempTooltip", "Temporary Bonus (adds to dice count)" },
                {"StatEpicTooltip", "Epic Bonus (adds raw successes to dice pool systems)" },
                //Inventory Tab & Pictures
                {"InventoryTab", "Inventory" },
                {"CharPictureField", "Portrait / Picture :" },
                {"CharPictureUrl", "Image URL or path" },
                {"CharPictureBrowse", "Browse..." },
                {"CharPictureClear", "Clear" },
                {"InventoryCapacityLabel", "Capacity :" },
                {"InventoryUnlimited", "Unlimited" },
                {"InventorySlotsUsed", "{0} / {1} slots" },
                {"InventoryAddItem", "Create Item" },
                {"InventoryManageTypes", "Manage Types" },
                {"InventorySearchPlaceholder", "Search items..." },
                {"InventoryFilterType", "Type :" },
                {"InventoryAllTypes", "All Types" },
                {"InventorySortBy", "Sort by :" },
                {"InventorySortName", "Name" },
                {"InventorySortType", "Type" },
                {"InventorySortQuantity", "Quantity" },
                {"InventorySortRarity", "Rarity" },
                {"InventoryNoItems", "No items in inventory." },
                {"InventoryItemDetails", "Item Details" },
                {"InventorySelectItemPrompt", "Select an item to view its details." },
                {"InventoryItemName", "Name :" },
                {"InventoryItemType", "Type :" },
                {"InventoryItemQuantity", "Quantity :" },
                {"InventoryItemMaxStack", "Max Stack :" },
                {"InventoryItemRarity", "Rarity :" },
                {"InventoryItemWeight", "Weight :" },
                {"InventoryItemDescription", "Description :" },
                {"InventoryItemEffect", "Effect(s) :" },
                {"InventoryItemImage", "Image (URL or local file) :" },
                {"InventoryItemCustomProps", "Custom Properties :" },
                {"InventoryAddProperty", "+ Property" },
                {"InventoryPropKey", "Key" },
                {"InventoryPropValue", "Value" },
                {"InventoryItemUse", "Use" },
                {"InventoryItemDuplicate", "Duplicate" },
                {"InventoryItemEdit", "Edit" },
                {"InventoryItemDelete", "Delete" },
                {"InventoryExportJson", "Copy JSON" },
                {"InventorySaveItem", "Save Item" },
                {"InventoryEditItemTitle", "Edit Item" },
                {"InventoryCreateItemTitle", "New Item" },
                {"InventoryManageTypesTitle", "Custom Item Types" },
                {"InventoryNewTypeName", "New type name" },
                {"InventoryAddTypeBtn", "Add Type" },
                {"InventoryCustomCapacity", "Custom Capacity :" },
                {"SystemInventoryLimitCheckbox", "System handles inventory capacity limit" },
                {"SystemInventorySlotsLabel", "Max inventory slots :" },
                {"InventoryImportJson", "Import" },
                {"InventoryImportTitle", "Import Items" },
                {"InventoryImportFileBtn", "JSON File..." },
                {"InventoryImportRawText", "Or paste raw JSON text:" },
                {"InventoryImportConfirmBtn", "Import to Inventory" },
                {"InventoryImportSuccess", "Successfully imported {0} item(s)!" },
                {"InventoryImportError", "Import error: {0}" },
                {"InventoryItemIsUsable", "Usable item" },
                {"InventoryItemFormula", "Use formula (e.g. 2d4+2, 10):" },
                {"InventoryItemFormulaHint", "e.g. 2d4+2, 1d8+3, 10" },
                {"InventoryItemNotUsable", "This item cannot be used." },
                {"InventoryItemUsedMessage", "Used {0}" },
                // Generic / Buttons / Dialogs
                {"CancelButton", "Cancel" },
                {"CloseButton", "Close" },
                {"DeleteButton", "Delete" },
                {"RemoveTooltip", "Remove" },
                {"NoneText", "None" },
                {"NoneOption", "(None)" },
                {"SelectButton", "Select" },
                {"EditButton", "Edit" },
                {"UnnamedCharacter", "Unnamed Character" },
                {"AgeYearsFormat", "{0} yrs" },
                {"ChooseCharPicPickerTitle", "Choose a character picture" },
                {"ChooseCharSheetPickerTitle", "Choose a character sheet" },
                {"BadgeEditing", "EDITING" },
                {"BadgeViewing", "VIEWING" },
                {"NewCharnameDefault", "New character" },
                {"NoCharLoadedMessage", "No character loaded. Create or load a character sheet above." },
                // Config Window
                {"ConfigWindowTitle", "Soulstone Settings" },
                {"ConfigRollDisplayHeader", "Roll Display Settings" },
                {"ConfigLocalizationHeader", "Language & Localization" },
                // Stat Window
                {"NoCharLoadedStatsMessage", "No character loaded. Load or create a character sheet first." },
                {"SystemDiceBadgeFormat", "Dice: {0}" },
                {"NoAttributesDefined", "No attributes defined." },
                {"NoSkillsDefined", "No skills defined." },
                {"NoAbilitiesDefined", "No abilities defined." },
                // Dice System Window
                {"NoDiceSysLoadedMessage", "No dice system loaded." },
                {"ChooseDiceSysPickerTitle", "Choose a dice system file" },
                {"DiceSysGeneralConfigHeader", "General Configuration" },
                {"DiceSysThresholdsHeader", "Success & Target Rules" },
                {"DiceSysFeaturesHeader", "Optional Mechanics & Rules" },
                {"TableHeaderLabel", "Label" },
                {"TableHeaderValue", "Value" },
                // Dice Window
                {"QuickDiceHeader", "Quick Dice" },
                {"DiceRollFormulaHint", "e.g. 2d6+4, 1d20+5" },
                {"ClearFormulaTooltip", "Clear formula" },
                {"BadgeAdvantage", "ADVANTAGE" },
                {"BadgeDisadvantage", "DISADVANTAGE" },
                {"NormalRollText", "Normal Roll" },
                {"RollHistoryHeader", "Roll History" },
                {"ClearHistoryButton", "Clear History" },
                {"NoRollHistoryMessage", "No rolls recorded yet in this session." },
                // Inventory Window
                {"NoCharLoadedInventoryMessage", "No character loaded. Create or load a character sheet first." },
                {"InventoryUnnamedItem", "Unnamed Item" },
                {"InventoryItemQtyFormat", "Qty: {0} / {1}" },
                {"InventoryItemWeightFormat", "Wt: {0:F1}" },
                {"InventoryItemUsableBadge", "Usable" },
                {"InventoryChoosePicPickerTitle", "Choose an item image" },
                {"InventoryStandardTypesHeader", "Standard Types:" },
                {"InventoryCustomTypesHeader", "Custom Types:" },
                {"InventoryNoCustomTypesMessage", "No custom types defined." },
                {"InventoryDeleteConfirmTitle", "Confirm Delete" },
                {"InventoryDeleteConfirmPrompt", "Are you sure you want to delete '{0}'?" },
                {"InventoryImportSelectJsonPrompt", "Select a JSON file containing an item or item list:" },
                {"InventoryImportPickerTitle", "Import items from JSON" },
                {"InventoryItemCopySuffix", " (Copy)" },
                // Standard Item Types
                {"ItemTypeGeneral", "General" },
                {"ItemTypeConsumable", "Consumable" },
                {"ItemTypeWeapon", "Weapon" },
                {"ItemTypeArmor", "Armor" },
                {"ItemTypeAccessory", "Accessory" },
                {"ItemTypeMaterial", "Material" },
                {"ItemTypeKeyItem", "Key Item" },
                {"ItemTypeQuest", "Quest" },
                {"ItemTypeMiscellaneous", "Miscellaneous" },
                // Rarities
                {"RarityCommon", "Common" },
                {"RarityUncommon", "Uncommon" },
                {"RarityRare", "Rare" },
                {"RarityEpic", "Epic" },
                {"RarityLegendary", "Legendary" },
                {"RarityArtifact", "Artifact" },
                // File Browser Window
                {"FileBrowserTitle", "Select File" },
                {"FileBrowserGoUpTooltip", "Go up one directory" },
                {"FileBrowserRefreshTooltip", "Refresh" },
                {"FileBrowserPathInputTooltip", "Type a path and press Enter to navigate" },
                {"FileBrowserFilterHint", "Filter files..." },
                {"FileBrowserUrlLabel", "URL:" },
                {"FileBrowserUrlHint", "https://example.com/image.png (or enter any direct web image URL)" },
                {"FileBrowserUrlTooltip", "Enter a web URL for the image" },
                {"FileBrowserPreviewButton", "Preview" },
                {"FileBrowserUseUrlButton", "Use URL" },
                {"FileBrowserQuickAccessHeader", "Quick Access" },
                {"FileBrowserPinnedHeader", "Pinned" },
                {"FileBrowserUnpinContext", "Unpin from Quick Access" },
                {"FileBrowserPinContext", "Pin to Quick Access" },
                {"FileBrowserRecentHeader", "Recent" },
                {"FileBrowserPictures", "Pictures" },
                {"FileBrowserDocuments", "Documents" },
                {"FileBrowserDesktop", "Desktop" },
                {"FileBrowserDownloads", "Downloads" },
                {"FileBrowserHome", "Home" },
                {"FileBrowserLocalDisk", "Local Disk" },
                {"FileBrowserFilesHeader", "Files" },
                {"FileBrowserSortName", "Name" },
                {"FileBrowserSortDate", "Date Modified" },
                {"FileBrowserSortSize", "Size" },
                {"FileBrowserSortType", "Type" },
                {"FileBrowserSortDesc", "Descending" },
                {"FileBrowserSortAsc", "Ascending" },
                {"FileBrowserOpenContext", "Open" },
                {"FileBrowserNoFilesFound", "No files found" },
                {"FileBrowserPreviewHeader", "Preview" },
                {"FileBrowserNoPreviewPrompt", "Select a file or enter a URL to preview" },
                {"FileBrowserWebImageUrl", "Web Image URL" },
                {"FileBrowserLoadingPreview", "Downloading / Loading image preview..." },
                {"FileBrowserFileNotFound", "File not found" },
                {"FileBrowserSelectedLabel", "Selected: {0}" },
                {"FileBrowserNoFileSelected", "No file selected" },
                // Group Management Window
                {"GroupManagementTitle", "Group Management" },
                {"GroupManagementSubtitle", "Party overview, live resource vitals, and peer synchronization." },
                {"GroupOpenWindow", "Group" },
                {"OpenGroupWindowTooltip", "Open Group Management" },
                {"GroupStatusConnected", "Soulstone Connected" },
                {"GroupStatusNoSoulstone", "No Soulstone" },
                {"GroupRulesetInSync", "In Sync" },
                {"GroupRulesetOutOfSync", "Different Ruleset" },
                {"GroupBadgeLeader", "DM / Leader" },
                {"GroupRefreshRoster", "Refresh Roster" },
                {"GroupBroadcastRuleset", "Broadcast Ruleset to Party" },
                {"GroupSyncInitiative", "Sync Party to Initiative" },
                {"GroupBroadcastVitals", "Share My Vitals" },
                {"GroupAdoptRuleset", "Adopt DM Ruleset" },
                {"GroupRevertRuleset", "Revert Local Ruleset" },
                {"GroupLastRoll", "Last Roll:" },
                {"GroupActiveBuffs", "Active Buffs:" },
                {"GroupHealth", "Health" },
                {"GroupMana", "Mana" },
                {"GroupNoMembers", "No party members detected." },
                {"GroupDMControls", "Dungeon Master Controls" },
                {"GroupPlayerControls", "Player Actions" },
                {"GroupSyncedFromDM", "Synced from Party Leader" },
                {"GroupRevertRulesetPrompt", "Restored local ruleset." },
                {"GroupAdoptConfirmPrompt", "Adopted DM ruleset for the session." },
                {"InitiativeDMBadge", "DM / Host" },
                {"InitiativeMemberBadge", "Synced Member" },
                {"InitiativeDMRequired", "Only the party leader / DM controls the round flow." },
                // Plugin
                {"PluginCommandHelp", "Opens the main window. Use '/soulstone init' for initiative and '/soulstone group' for group management." }
            };

            LocalizedLanguages[Language.Français] = French;
            LocalizedLanguages[Language.English] = English;

        }

        public string GetLocalizedString(string fieldName)
        {
            string value = fieldName;
            Language language = configuration?.Language ?? Language.Français;
            if (localizedLanguages.TryGetValue(language, out var locstrings) && locstrings != null)
            {
                if (language != locstrings.Language)
                {
                    Plugin.Log.Error($"Error : Language mismatch between {language.ToString()} and {locstrings.Language.ToString()}");
                }
                if (locstrings.LocalizedStrings.TryGetValue(fieldName, out var localizedValue))
                {
                    value = localizedValue;
                }
            }
            else
            {
                Plugin.Log.Error("Error : Language not found.");
            }

            return value;
        }
    }
}
